// This file is autogenerated by docs/plugins/content.ts.
// Do not edit it directly.
import { lazy, type Component } from "solid-js"

export type DocHeading = {
  depth: number
  slug: string
  text: string
}

export type DocData = {
  title: string
  description: string
  navTitle?: string
  section: string
  order?: number
  status?: string
  toc: boolean
}

export type DocEntry = {
  component: Component
  data: DocData
  headings: DocHeading[]
}

export type DocsNavSection = {
  title: string
  items: Array<{
    title: string
    href: string
    description: string
    status?: string
  }>
}

export const Contents: Record<string, DocEntry> = {

}

export const docsNavigation: DocsNavSection[] = []
