import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { dirname, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import GithubSlugger from "github-slugger"
import grayMatter from "gray-matter"
import type { Plugin } from "vite"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const docsDirectory = resolve(__dirname, "../src/content/docs")
const outputFile = resolve(__dirname, "../src/content/index.ts")

type DocFrontmatter = {
  title?: string
  description?: string
  navTitle?: string
  section?: string
  order?: number
  status?: string
  toc?: boolean
}

type DocHeading = {
  depth: number
  slug: string
  text: string
}

type DocEntry = {
  componentPath: string
  key: string
  data: Required<Pick<DocFrontmatter, "title" | "description" | "section" | "toc">> &
    Omit<DocFrontmatter, "title" | "description" | "section" | "toc">
  headings: DocHeading[]
}

const walk = (directory: string): string[] => {
  return readdirSync(directory).flatMap((entry) => {
    const absolutePath = resolve(directory, entry)
    const stats = statSync(absolutePath)

    if (stats.isDirectory()) {
      return walk(absolutePath)
    }

    return absolutePath.endsWith(".mdx") ? [absolutePath] : []
  })
}

const normalizeHeadingText = (value: string): string => {
  return value
    .replace(/\[(.*?)\]\(.*?\)/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/[*_~]/g, "")
    .trim()
}

const extractHeadings = (content: string): DocHeading[] => {
  const headings: DocHeading[] = []
  const slugger = new GithubSlugger()
  let inCodeBlock = false

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim()

    if (/^(```|~~~)/.test(trimmed)) {
      inCodeBlock = !inCodeBlock
      continue
    }

    if (inCodeBlock) {
      continue
    }

    const match = /^(#{1,6})\s+(.*)$/.exec(trimmed)
    if (!match || !match[1] || !match[2]) {
      continue
    }

    const hashes = match[1]
    const rawText = match[2]
    const text = normalizeHeadingText(rawText)
    if (!text) {
      continue
    }

    headings.push({
      depth: hashes.length,
      slug: slugger.slug(text),
      text,
    })
  }

  return headings
}

const toTitleCase = (value: string): string =>
  value
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase())

const createDocEntry = (absolutePath: string): DocEntry => {
  const fileContent = readFileSync(absolutePath, "utf8")
  const { data, content } = grayMatter(fileContent)
  const frontmatter = data as DocFrontmatter
  const key = relative(docsDirectory, absolutePath).replace(/\\/g, "/").replace(/\.mdx$/, "")
  const segments = key.split("/")
  const fallbackTitle = toTitleCase(segments[segments.length - 1] ?? key)
  const fallbackSection = segments.length > 1 ? toTitleCase(segments[0] ?? "general") : "General"

  return {
    key,
    componentPath: `@docs/content/docs/${key}.mdx`,
    data: {
      title: frontmatter.title ?? fallbackTitle,
      description: frontmatter.description ?? "",
      navTitle: frontmatter.navTitle ?? frontmatter.title ?? fallbackTitle,
      section: frontmatter.section ?? fallbackSection,
      order: frontmatter.order ?? 0,
      status: frontmatter.status,
      toc: frontmatter.toc ?? true,
    },
    headings: extractHeadings(content),
  }
}

const generateFileContent = (entries: DocEntry[]): string => {
  const sections = new Map<
    string,
    {
      title: string
      items: Array<{
        title: string
        href: string
        description: string
        status?: string
      }>
    }
  >()

  for (const entry of entries) {
    const section = sections.get(entry.data.section) ?? {
      title: entry.data.section,
      items: [],
    }

    section.items.push({
      title: entry.data.navTitle ?? entry.data.title,
      href: `/docs/${entry.key}`,
      description: entry.data.description,
      status: entry.data.status,
    })

    sections.set(entry.data.section, section)
  }

  const groupedSections = Array.from(sections.values())

  const contentRecords = entries
    .map((entry) => {
      return `  "${entry.key}": {
    component: lazy(() => import("${entry.componentPath}")),
    data: ${JSON.stringify(entry.data, null, 4)},
    headings: ${JSON.stringify(entry.headings, null, 4)}
  },`
    })
    .join("\n")

  return `// This file is autogenerated by docs/plugins/content.ts.
// Do not edit it directly.
import { lazy, type Component } from "solid-js"

export type DocHeading = {
  depth: number
  slug: string
  text: string
}

export type DocData = {
  title: string
  description: string
  navTitle?: string
  section: string
  order?: number
  status?: string
  toc: boolean
}

export type DocEntry = {
  component: Component
  data: DocData
  headings: DocHeading[]
}

export type DocsNavSection = {
  title: string
  items: Array<{
    title: string
    href: string
    description: string
    status?: string
  }>
}

export const Contents: Record<string, DocEntry> = {
${contentRecords}
}

export const docsNavigation: DocsNavSection[] = ${JSON.stringify(groupedSections, null, 2)}
`
}

const sortEntries = (entries: DocEntry[]): DocEntry[] => {
  return [...entries].sort((left, right) => {
    if (left.data.section !== right.data.section) {
      return left.data.section.localeCompare(right.data.section)
    }

    if ((left.data.order ?? 0) !== (right.data.order ?? 0)) {
      return (left.data.order ?? 0) - (right.data.order ?? 0)
    }

    return left.data.title.localeCompare(right.data.title)
  })
}

const generateContentsFile = () => {
  mkdirSync(resolve(__dirname, "../src/content"), { recursive: true })
  const entries = sortEntries(walk(docsDirectory).map(createDocEntry))
  writeFileSync(outputFile, generateFileContent(entries))
}

export default (): Plugin => {
  return {
    name: "docs-content",
    buildStart() {
      generateContentsFile()
    },
    configureServer(server) {
      const refresh = (path: string) => {
        if (!path.endsWith(".mdx")) {
          return
        }

        generateContentsFile()
      }

      server.watcher.on("add", refresh)
      server.watcher.on("change", refresh)
      server.watcher.on("unlink", refresh)
    },
  }
}
